aliases:
    apply-brens-home-pc: nix run --impure home-manager/master -- -b bak switch --flake .#bingham@brens-home-pc
    fleeks: cd ~/.local/share/fleek
allow_broken: false
auto_gc: false
bling: high
blocklist:
    - vscode
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - adw-gtk3
    - lsd
    - zsh
    - fd
    - awscli2
    - bws
    - bitwarden-cli
    - volta
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.volta/bin
programs:
    - dircolors
    - kitty
    - tmux
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: brens-home-pc
      os: linux
      user:
        email: brendan@ingham.dev
        name: Brendan Ingham
        ssh_private_key_file: /home/bingham/.ssh/id_ed25519
        ssh_public_key_file: /home/bingham/.ssh/id_ed25519.pub
        username: bingham
      username: bingham
    - arch: aarch64
      home: ""
      hostname: brens-macbook-pro.local
      os: darwin
      user:
        email: brendan.ingham@cinch.co.uk
        name: Brendan Ingham
        ssh_private_key_file: ~/.ssh/id_ed25519
        ssh_public_key_file: ~/.ssh/id_ed25519.pub
        username: bingham
      username: bingham
track: nixos-unstable
unfree: true
users:
    - email: brendan@ingham.dev
      name: Brendan Ingham
      ssh_private_key_file: /home/bingham/.ssh/id_ed25519
      ssh_public_key_file: /home/bingham/.ssh/id_ed25519.pub
      username: bingham
