aliases:
    apply-brens-home-pc: nix run --impure home-manager/master -- -b bak switch --flake .#bingham@brens-home-pc
    fleeks: cd ~/.local/share/fleek
allow_broken: false
auto_gc: false
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: .local/share/fleek
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - helix
    - adw-gtk3
    - volta
    - lsd
    - zsh
    - lazygit
    - jq
    - neofetch
    - btop
    - atuin
    - zoxide
    - fd
    - awscli2
    - bws
    - bitwarden-cli
    - direnv
    - github-cli
    - starship
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/.volta/bin
programs:
    - dircolors
shell: bash
systems:
    - arch: x86_64
      home: ""
      hostname: brens-home-pc
      os: linux
      user:
        email: brendan@ingham.dev
        name: Brendan Ingham
        ssh_private_key_file: /home/bingham/.ssh/id_ed25519
        ssh_public_key_file: /home/bingham/.ssh/id_ed25519.pub
        username: bingham
      username: bingham
track: nixos-unstable
unfree: true
users:
    - email: brendan@ingham.dev
      name: Brendan Ingham
      ssh_private_key_file: /home/bingham/.ssh/id_ed25519
      ssh_public_key_file: /home/bingham/.ssh/id_ed25519.pub
      username: bingham
